const Request = require('request');
const Hawk = require('hawk');


// Client credentials
const credentials = {
    id: 'dh37fgj492je',
    key: 'werxhqb98rpaxn39848xrunpaw3489ruxnpa98w4rxn',
    algorithm: 'sha256'
};

// Request options
const requestOptions = {
    uri: 'http://localhost:8000/lenddo',
    method: 'GET',
    headers: {}
};

const testHandler = (res) => {

    // Generate Authorization request header
    const { header } = Hawk.client.header('http://localhost:8000/lenddo', 'GET', {
        credentials: credentials
    });
    requestOptions.headers.Authorization = header;
    console.log('header generated by hawk', header);

    // Send authenticated request
    Request(requestOptions, function (error, response, body) {
        //console.log('body', body);

        // Authenticate the server's response
        const isValid = Hawk.client.authenticate(response, credentials, header.artifacts, {payload: body});
        console.log('isValid', isValid);
        //console.log(error, response, body);

        // Output results
        //console.log(`${response.statusCode}: ${body}` + (isValid ? ' (valid)' : ' (invalid)'));

        res.status(200).send({error, response, body});
    });

};

module.exports = testHandler;